
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dev
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            //============================================FUNCTION===============================
        public void ItemCost()
        {
            double sum = 0;
            
            for (int i = 0; i  <jTable1.getRowCount(); i++)
            {
                sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
            }
            jtxtSubTotal.setText(Double.toString(sum));
            double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
            
            double cTax = (cTotal1 * 3.9)/100;
            String iTaxTotal = String.format("£ %.2f", cTax);
            jtxtTax.setText(iTaxTotal);
            
            String iSubTotal = String.format("£ %.2f", cTotal1);
            jtxtSubTotal.setText(iSubTotal);
            
            String iTotal = String.format("£ %.2f", cTotal1 + cTax);
            jtxtTotal.setText(iTotal);
            
            String BarCode = String.format("Total is %.2f", cTotal1 + cTax);
            jtxtBarCode.setText(BarCode);
        }
        
            //============================function change===============================================
        
        public void Change()
        {
            double sum =0;
            double tax =3.9;
            double cash = Double.parseDouble(jtxtDisplay.getText());
            
            for (int i = 0; i  <jTable1.getRowCount(); i++)
            {
                sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
            }
            
            double cTax = (sum *3.9/100);
            double cChange = (cash - (sum + cTax));
            
            String ChangeGiven = String.format("£ %.2f", cChange);
            jtxtChange.setText(ChangeGiven);
        }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbtnCheseCake = new javax.swing.JButton();
        jbtnChokoShake = new javax.swing.JButton();
        jbtnMangoIcecream = new javax.swing.JButton();
        jbtnIcecreamCone = new javax.swing.JButton();
        jbtnBrowni = new javax.swing.JButton();
        jbtnStrawberryShake = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtn1 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnc = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCheseCake.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnCheseCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cck.jpg"))); // NOI18N
        jbtnCheseCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheseCakeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCheseCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 250, 190));

        jbtnChokoShake.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnChokoShake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/4.jpg"))); // NOI18N
        jbtnChokoShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChokoShakeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnChokoShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 250, 190));

        jbtnMangoIcecream.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnMangoIcecream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mango.jpg"))); // NOI18N
        jbtnMangoIcecream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMangoIcecreamActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMangoIcecream, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 240, 190));

        jbtnIcecreamCone.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnIcecreamCone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/88.jpg"))); // NOI18N
        jbtnIcecreamCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIcecreamConeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnIcecreamCone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 250, 190));

        jbtnBrowni.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnBrowni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/5.jpg"))); // NOI18N
        jbtnBrowni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowniActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 190));

        jbtnStrawberryShake.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnStrawberryShake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2.jpg"))); // NOI18N
        jbtnStrawberryShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStrawberryShakeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnStrawberryShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 250, 190));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Browni");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("milk Shake");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Mango ice cream");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("chese cake");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Ice cream Cone");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Choko Shake");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 880, 540));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 130));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 120, 130));

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 130));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 130));

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 120, 130));

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 120, 130));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 120, 130));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 120, 130));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 130));

        jbtnDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 120, 130));

        jbtnc.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jbtnc.setText("c");
        jbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 120, 130));

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 580));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Ammunt"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 390, 470));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tax");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Total");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("SubTotal");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 250, 40));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 250, 40));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel4.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 250, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 470, 190));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Change");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 250, 40));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 250, 40));

        jcboPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card", "Rupee Card" }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });
        jPanel6.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 230, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Cash");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Payment Method");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 550, 190));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 280, 50));

        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 50));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 50));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 570, 50));

        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 280, 50));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 590, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 1690, 230));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP24DhTt", 0, 55)); // NOI18N
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 390, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn1.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn1.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn0.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn0.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn8.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn8.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn4.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn4.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn9.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn9.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:String Enternumber = jtxtDisplay.getText();
         String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn5.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn5.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn6.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn6.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn2.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn2.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn3.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn3.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        // TODO add your handling code here:
        
        if(! jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText( jtxtDisplay.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncActionPerformed
        // TODO add your handling code here:
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtncActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
         // TODO add your handling code here:
         String Enternumber = jtxtDisplay.getText();
         
         if (Enternumber == "")
         {
             jtxtDisplay.setText(jbtn7.getText());
         }
         else
         {
             Enternumber = jtxtDisplay.getText() + jbtn7.getText();
             jtxtDisplay.setText(Enternumber);
         }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtnCheseCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheseCakeActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 4.50;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"chese cake", "1", PriceOfItem}); 
        ItemCost();
    }//GEN-LAST:event_jbtnCheseCakeActionPerformed

    private void jbtnChokoShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChokoShakeActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 3.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"cadbury shake", "1", PriceOfItem}); 
        ItemCost();
    }//GEN-LAST:event_jbtnChokoShakeActionPerformed

    private void jbtnIcecreamConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIcecreamConeActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 1.00;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"chocolate cone", "1", PriceOfItem}); 
        ItemCost();
    }//GEN-LAST:event_jbtnIcecreamConeActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed

    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Point of Sale",
                JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnBrowniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowniActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 3.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Browni", "1", PriceOfItem}); 
        ItemCost();
        
    }//GEN-LAST:event_jbtnBrowniActionPerformed

    private void jbtnStrawberryShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStrawberryShakeActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 1.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"strawberry shake", "1", PriceOfItem}); 
        ItemCost();
    }//GEN-LAST:event_jbtnStrawberryShakeActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        // TODO add your handling code here:
        if (jcboPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnMangoIcecreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMangoIcecreamActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 2.75;

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"mango icecream", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnMangoIcecreamActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Your bill.");
        MessageFormat footer = new MessageFormat("page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header,footer);
        }
        
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int RemoveItem = jTable1.getSelectedRow();
        if(RemoveItem >= 0)
        {
            model.removeRow(RemoveItem);
        }
        ItemCost();
        
         if (jcboPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBrowni;
    private javax.swing.JButton jbtnCheseCake;
    private javax.swing.JButton jbtnChokoShake;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnIcecreamCone;
    private javax.swing.JButton jbtnMangoIcecream;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnStrawberryShake;
    private javax.swing.JButton jbtnc;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
